//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ChequeProcessing.CPSWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetAccountInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAccountInfoForCPSOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSignatoriesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSignatureOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::ChequeProcessing.Properties.Settings.Default.ChequeProcessing_CPSWS_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAccountInfoCompletedEventHandler GetAccountInfoCompleted;
        
        /// <remarks/>
        public event GetAccountInfoForCPSCompletedEventHandler GetAccountInfoForCPSCompleted;
        
        /// <remarks/>
        public event GetSignatoriesCompletedEventHandler GetSignatoriesCompleted;
        
        /// <remarks/>
        public event GetSignatureCompletedEventHandler GetSignatureCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAccountInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AccountInfo GetAccountInfo(string AccountNo) {
            object[] results = this.Invoke("GetAccountInfo", new object[] {
                        AccountNo});
            return ((AccountInfo)(results[0]));
        }
        
        /// <remarks/>
        public void GetAccountInfoAsync(string AccountNo) {
            this.GetAccountInfoAsync(AccountNo, null);
        }
        
        /// <remarks/>
        public void GetAccountInfoAsync(string AccountNo, object userState) {
            if ((this.GetAccountInfoOperationCompleted == null)) {
                this.GetAccountInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAccountInfoOperationCompleted);
            }
            this.InvokeAsync("GetAccountInfo", new object[] {
                        AccountNo}, this.GetAccountInfoOperationCompleted, userState);
        }
        
        private void OnGetAccountInfoOperationCompleted(object arg) {
            if ((this.GetAccountInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAccountInfoCompleted(this, new GetAccountInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAccountInfoForCPS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AccountResult GetAccountInfoForCPS(string AccountNo) {
            object[] results = this.Invoke("GetAccountInfoForCPS", new object[] {
                        AccountNo});
            return ((AccountResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetAccountInfoForCPSAsync(string AccountNo) {
            this.GetAccountInfoForCPSAsync(AccountNo, null);
        }
        
        /// <remarks/>
        public void GetAccountInfoForCPSAsync(string AccountNo, object userState) {
            if ((this.GetAccountInfoForCPSOperationCompleted == null)) {
                this.GetAccountInfoForCPSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAccountInfoForCPSOperationCompleted);
            }
            this.InvokeAsync("GetAccountInfoForCPS", new object[] {
                        AccountNo}, this.GetAccountInfoForCPSOperationCompleted, userState);
        }
        
        private void OnGetAccountInfoForCPSOperationCompleted(object arg) {
            if ((this.GetAccountInfoForCPSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAccountInfoForCPSCompleted(this, new GetAccountInfoForCPSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSignatories", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetSignatories(string AccountNo) {
            object[] results = this.Invoke("GetSignatories", new object[] {
                        AccountNo});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetSignatoriesAsync(string AccountNo) {
            this.GetSignatoriesAsync(AccountNo, null);
        }
        
        /// <remarks/>
        public void GetSignatoriesAsync(string AccountNo, object userState) {
            if ((this.GetSignatoriesOperationCompleted == null)) {
                this.GetSignatoriesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSignatoriesOperationCompleted);
            }
            this.InvokeAsync("GetSignatories", new object[] {
                        AccountNo}, this.GetSignatoriesOperationCompleted, userState);
        }
        
        private void OnGetSignatoriesOperationCompleted(object arg) {
            if ((this.GetSignatoriesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSignatoriesCompleted(this, new GetSignatoriesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSignature", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RetData GetSignature(string icref) {
            object[] results = this.Invoke("GetSignature", new object[] {
                        icref});
            return ((RetData)(results[0]));
        }
        
        /// <remarks/>
        public void GetSignatureAsync(string icref) {
            this.GetSignatureAsync(icref, null);
        }
        
        /// <remarks/>
        public void GetSignatureAsync(string icref, object userState) {
            if ((this.GetSignatureOperationCompleted == null)) {
                this.GetSignatureOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSignatureOperationCompleted);
            }
            this.InvokeAsync("GetSignature", new object[] {
                        icref}, this.GetSignatureOperationCompleted, userState);
        }
        
        private void OnGetSignatureOperationCompleted(object arg) {
            if ((this.GetSignatureCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSignatureCompleted(this, new GetSignatureCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AccountInfo {
        
        private string accountnoField;
        
        private string customernameField;
        
        private string currencyField;
        
        private string availablebalanceField;
        
        private string reservedbalanceField;
        
        private bool blockedField;
        
        private bool inactiveField;
        
        private bool closingField;
        
        private bool decOrLiqField;
        
        private string typeField;
        
        /// <remarks/>
        public string accountno {
            get {
                return this.accountnoField;
            }
            set {
                this.accountnoField = value;
            }
        }
        
        /// <remarks/>
        public string customername {
            get {
                return this.customernameField;
            }
            set {
                this.customernameField = value;
            }
        }
        
        /// <remarks/>
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        public string availablebalance {
            get {
                return this.availablebalanceField;
            }
            set {
                this.availablebalanceField = value;
            }
        }
        
        /// <remarks/>
        public string reservedbalance {
            get {
                return this.reservedbalanceField;
            }
            set {
                this.reservedbalanceField = value;
            }
        }
        
        /// <remarks/>
        public bool blocked {
            get {
                return this.blockedField;
            }
            set {
                this.blockedField = value;
            }
        }
        
        /// <remarks/>
        public bool inactive {
            get {
                return this.inactiveField;
            }
            set {
                this.inactiveField = value;
            }
        }
        
        /// <remarks/>
        public bool closing {
            get {
                return this.closingField;
            }
            set {
                this.closingField = value;
            }
        }
        
        /// <remarks/>
        public bool decOrLiq {
            get {
                return this.decOrLiqField;
            }
            set {
                this.decOrLiqField = value;
            }
        }
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RetData {
        
        private string imageDataField;
        
        private string sPINSTField;
        
        /// <remarks/>
        public string ImageData {
            get {
                return this.imageDataField;
            }
            set {
                this.imageDataField = value;
            }
        }
        
        /// <remarks/>
        public string SPINST {
            get {
                return this.sPINSTField;
            }
            set {
                this.sPINSTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AccountResult {
        
        private string accountInfoField;
        
        private bool stopPaymentField;
        
        /// <remarks/>
        public string AccountInfo {
            get {
                return this.accountInfoField;
            }
            set {
                this.accountInfoField = value;
            }
        }
        
        /// <remarks/>
        public bool StopPayment {
            get {
                return this.stopPaymentField;
            }
            set {
                this.stopPaymentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetAccountInfoCompletedEventHandler(object sender, GetAccountInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAccountInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAccountInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AccountInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AccountInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetAccountInfoForCPSCompletedEventHandler(object sender, GetAccountInfoForCPSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAccountInfoForCPSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAccountInfoForCPSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AccountResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AccountResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetSignatoriesCompletedEventHandler(object sender, GetSignatoriesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSignatoriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSignatoriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetSignatureCompletedEventHandler(object sender, GetSignatureCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSignatureCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSignatureCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RetData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RetData)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591