//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace ChequeProcessing.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        public Guid LoadedBatchID { get; set; }
        public string BatchCurrency { get; set; }
        public bool AllBranch { get; set; }

        public int RoleID { get; set; }

        public string RoleCD { get; set; }
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:1271/CbsNameLookUp.asmx")]
        public string ChequeProcessing_GetNamesService_CbsNameLookUp {
            get {
                return ((string)(this["ChequeProcessing_GetNamesService_CbsNameLookUp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.129.57/cbs_ws/CBS_Master.asmx")]
        public string RTGS_DHBLWS_CBS_Master {
            get {
                return ((string)(this["RTGS_DHBLWS_CBS_Master"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/FloraRTGSWS/Service1.asmx")]
        public string ChequeProcessing_CPSWS_Service1 {
            get {
                return ((string)(this["ChequeProcessing_CPSWS_Service1"]));
            }
        }
    }
}
